In [0]:
pip install firebase_admin

     |████████████████████████████████| 92kB 3.1MB/s 
     |████████████████████████████████| 337kB 8.9MB/s 
     |████████████████████████████████| 81kB 10.1MB/s 
ERROR: google-cloud-storage 1.25.0 has requirement google-auth<2.0dev,>=1.9.0, but you'll have google-auth 1.4.2 which is incompatible.
ERROR: google-cloud-storage 1.25.0 has requirement google-cloud-core<2.0dev,>=1.2.0, but you'll have google-cloud-core 1.0.3 which is incompatible.
ERROR: google-cloud-bigquery 1.21.0 has requirement google-resumable-media!=0.4.0,<0.5.0dev,>=0.3.1, but you'll have google-resumable-media 0.5.0 which is incompatible.
  Found existing installation: google-resumable-media 0.4.1
    Uninstalling google-resumable-media-0.4.1:
      Successfully uninstalled google-resumable-media-0.4.1
  Found existing installation: google-cloud-storage 1.16.2
    Uninstalling google-cloud-storage-1.16.2:
      Successfully uninstalled google-cloud-storage-1.16.2


In [0]:
from keras.layers import Dense, LSTM, Input, Dropout, Bidirectional
from keras.models import Model, load_model
import numpy as np
import random as rand
from math import log10, log
import datetime
import firebase_admin
from firebase_admin import credentials, storage
from urllib.request import urlretrieve
from flask import Flask, request
import json
import threading
import requests

def retrain(model, data, epochs):
  x_train = data[0]
  y_train = data[1]
  model.fit(np.array(x_train), np.array(y_train), epochs=epochs)
  return model

def predict(model, previous_grades, required_grades, timesteps):
  variation = 0.1
  generations = 3
  best = [0 if required_grades[i] == 0 else required_grades[i] - previous_grades[i] for i in range(15)]
  best.append(1)
  variations = [0 if i == 0 else variation for i in previous_grades]
  variations.append(variation)
  random_outputs, no_tries = [], 30
  for output in range(no_tries):
    temp = []
    for i in range(timesteps):
      index = np.argmax(np.random.normal(best, variations))
      temp.append(np.array([0 if i != index else 1 for i in range(16)]))
    random_outputs.append(np.asarray(temp))
  errors = []
  for output in random_outputs:
    y_true, y_pred = required_grades, model.predict(np.array([output]))[0]
    error = sum([((y_true[i] - y_pred[i] + abs(y_true[i] - y_pred[i])) ** 2) / 4 for i in range(len(y_true))])
    errors.append(error)
  best = random_outputs[np.argmin(errors)]
  for i in range(generations - 1):
    random_outputs, no_tries = [best], 30
    for output in range(no_tries):
      temp = []
      for i in range(timesteps):
        index = np.argmax(np.random.normal(best[i], variations))
        temp.append(np.array([0 if i != index else 1 for i in range(16)]))
      random_outputs.append(np.asarray(temp))
    errors = []
    for output in random_outputs:
      y_true, y_pred = required_grades, model.predict(np.array([output]))[0]
      error = sum([((y_true[i] - y_pred[i] + abs(y_true[i] - y_pred[i])) ** 2) / 4 for i in range(len(y_true))])
      errors.append(error)
    best = random_outputs[np.argmin(errors)]
  return best

def start(subjects):
  attainments = [5,6,7,8]
  models = []
  for attainment in attainments:
    x_train, y_train, x_test, y_test = simulate_users(attainment, subjects)
    input_shape = None, x_train.shape[2]
    output_shape = y_train.shape[1] 
    model = build_model(input_shape, output_shape)
    model.fit(x_train, y_train, epochs=250, batch_size=2800, validation_data=(x_test, y_test))
    models.append(model)
  return models

def simulate_users(attainment, subjects):
  variation = 0
  datapoints, periods = 3000, 10
  x, subject_idxs = generate_input_data(subjects, periods, datapoints, attainment)
  y = generate_output_data(x, attainment, variation, subject_idxs)
  y = format_output_data(y)
  x_test, x_train = x[:200], x[200:]
  y_test, y_train = y[:200], y[200:]
  return x_train, y_train, x_test, y_test

def build_model(input_shape, output_shape):
  input_subject = Input(shape=(input_shape))
  layer_1 = Bidirectional(LSTM(128, recurrent_dropout=0.7))(input_subject)
  output = Dense(output_shape, activation='sigmoid')(layer_1)
  model = Model(input_subject, output)
  model.compile(loss="categorical_crossentropy", optimizer='adam', metrics=['accuracy'])
  return model

def generate_input_data(subjects, periods, datapoints, attainment):
  x, list_of_subject_idxs = [], []
  for i in range(datapoints):
    subject_idxs = rand.sample(range(15), subjects)
    subject_idxs_with_rests = [i for i in subject_idxs]
    subject_idxs_with_rests.append(15)
    list_of_subject_idxs.append(subject_idxs)
    datapoint = []
    for i in range(periods):
      subject_idx = rand.choice(subject_idxs_with_rests)
      subject_ohe = np.linspace(0, 0, 16)
      subject_ohe[subject_idx] = 1
      datapoint.append(subject_ohe)
    datapoint = np.asarray(datapoint)
    x.append(datapoint)
  x = np.asarray(x)
  return x, list_of_subject_idxs

def generate_output_data(x, attainment, variation, subject_idxs):
  dist_weighting = -0.02
  adj_break_weighting = 0.6
  adj_subj_weighting = -0.2
  y = []
  for j, datapoint in enumerate(x):
    length = len(datapoint)
    efficient_time_studied, grade = [0 for i in range(16)], [0 for i in range(15)]
    for i, period in enumerate(datapoint):
      distance = length - i
      rest, same = 0, 0
      if np.argmax(datapoint[i - 1]) == 15:
        rest = 1
      elif np.argmax(datapoint[i - 1]) == np.argmax(period):
        same = 1
      efficient_time_studied[np.argmax(period)] += 1 + dist_weighting * distance + adj_break_weighting * rest + adj_subj_weighting * same
    for i in subject_idxs[j]:
      grade[i] = np.random.normal((2.37089 + 0.602646 * attainment + (3.63039 - 0.330035 * attainment) * log(0.3 + 0.9 * efficient_time_studied[i])), variation)
    for i in range(len(grade)):
      if grade[i] == 0.:
        grade[i] = 5.
    y.append(grade)
  y = np.asarray(y)
  return y

def format_output_data(y_unformatted):
  y_formatted = y_unformatted / 9
  return y_formatted

def generate_timetable(inputs):
  epochs = len(inputs["training_data"]["x"]) * 5 ## this multiplier can be optimised
  if inputs["training_data"]["x"] != []:
    model = retrain(load_model("model_attainment_" + inputs["attainment"] + ".h5"), (inputs["training_data"]["x"], inputs["training_data"]["y"]), epochs)
  else:
    model = load_model("model_attainment_" + inputs["attainment"] + ".h5")
  output = predict(model, inputs["prediction_data"]["past_grades"], inputs["prediction_data"]["required_grades"], inputs["prediction_data"]["hours"])
  return output

credentials_for_json = {
  "type": "service_account",
  "project_id": "maximise-uk",
  "private_key_id": "ee4f4bfedd72bcc729c76c1e0c67d5c01e5b96b9",
  "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDZtZE8B2j6HUFd\nLpmF2EoKZmqpVlwLR/ymi8U+06DZYlgL6KW+cjArrxglibMw6p8shgJxkFh5DZXS\nk02wPCJrmKC+7wIIhPGiTHs0ji2b7RisEZl4Vgu2cdIR5IowMtds6HxhqjeCdVc4\nIZ5VeiAqyA9gQW/thcTG7OcX0tcEynOYz9KuaCnWZYgG93Tl+aQQKm+mCsu3GleV\ngXklS0sjB9HkevLaxcQLoCcg68Se7rSSWSrBguOSZ3SPjdvgJpsr09UoTA+9Spbu\nRpC9avXoxrA0Tx+X0Z9rvRF8jYxOQwL2OkLCrpK3TCYCarbLUqax0oKtZ0LpBDcy\nke/efi3zAgMBAAECggEAJ9VPwHL+oxytM/Ztwo6DZYm9pEQXzTybnoFeUpN4D64t\nu+gSQ1kzNRrxSRT7w0x6WTQfyFWHyoZQzlmDUmZ+Sb+AUc77SUHB0Fc8B66n66qi\n5ADIWrsro3MJ45o0KoNy5QtYjqoNRAJiNfP4u1z/+7PlFFCEwSnDij4YPkSmcMqf\nnHyUPwxPvcUp2CAkeKjrV3UXEjdQ0wkh4hv6yMcXnGGDNknwEAEQ7may+BA81eAW\nYky+ItP4qAauXHxJQBNG9iy9Win+BXQzFanF3ZmpyRtPjsfShuuFUNRncDt64E80\nO7esMEQdjIlhMeSwZkWVob1U0l7nH5PCyRjfOwLxIQKBgQDu6Oq2eFmuUchBTZGa\na/gAQ171g3dPCA4nhMoZM+beJM7tKrpTGb2S0B5yHpBd8llWkBIHnmEoFgPOZgPa\nIt2GEK/ntOsvM4DYUSA6EizFUwLSLUDDIE34mvPehfakLM8Wh0Li/clzlZ58pvBv\nhkVl3P/WBLLV8dDTalCNtGgS8QKBgQDpSGkecH/JuAwGB47fxoOdWCzs8f+DjP8P\nRH3MQNtwp7DSSLRXNc9niQM/Ot1Fc8DOvxwxxUyR9iMqcHKiiPJsts4HItHq/WlR\nxyAoRNGewKdk+Y4hZhIh0rEna8cce9ggNRGiw8HK2g2GnbomPj3eJdK5/MNWmkT+\nyBIQ+a8HIwKBgA0fnkUHt2Vr+KQdrrHc3HKnQMAbyKH+v0hMcw2PXE83lmZQwotu\nDovSAtoh86w1c9LddyAUAyJAk1TzJaMF50VGBWOk/IZLPfij/DE0bmEofi8tbTFK\nxP2zBVJj6Xh7PaTvKS1u43IF9f7C7NIzffxqd2M6Ptihv+bdIC+oiU8BAoGBAOWT\nzV+XdysdZTfJ2GGBC6WdURkeT0c3SwvLa8HHUi3b2bgYtOHeou5ReFCRrZDcCbNt\ngGG6uVAr2w+4+hfajjlO7hM3wT5xhWRlgtAeaezBy/sjXSyhNtbyckVJW/o8JsYL\nc/+qht0LGqSQNNHODzTAJFHE3rgruhrC6oSqNAXhAoGAXzB4POvZDXNTNRIAhMJ4\no1PCooAq6K3WmGyAOV7+hQxS9IyShhIIqTG3B+fXoEgz/aaHwp+w1c83MSiiQWH1\nZh0mB/Eer50iEPfECyhF8sPTW+Hk5KMUQSTZkkVximpQ7rszrb4JOrsjegCBP01s\nOynEJrkUc6IZH/a/LLy1+90=\n-----END PRIVATE KEY-----\n",
  "client_email": "firebase-adminsdk-zduqr@maximise-uk.iam.gserviceaccount.com",
  "client_id": "101775960412756890600",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://oauth2.googleapis.com/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-zduqr%40maximise-uk.iam.gserviceaccount.com"
}

with open("credentials.json", "w") as write_file:
    json.dump(credentials_for_json, write_file)

cred = credentials.Certificate("credentials.json")
app = firebase_admin.initialize_app(cred, {
    'storageBucket': 'maximise-uk.appspot.com',
}, name='storage')
bucket = storage.bucket(app=app)
for i in range(5, 9):
  blob = bucket.blob(f"model_attainment_{i}.h5")
  urlretrieve(blob.generate_signed_url(datetime.timedelta(seconds=300), method='GET'), f'model_attainment_{i}.h5')

app = Flask(__name__)
@app.route("/", methods=["POST"])
def generate_ml():
    inputs = request.get_json()
    output = generate_timetable(inputs)
    return str(output)
threading.Thread(target=app.run, kwargs={'host':'0.0.0.0','port':80}).start()

Using TensorFlow backend.


 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)


In [0]:
inputs = {
  "attainment": "8",
  "training_data": {
      "x": [[[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]]],
      "y": [[8, 5, 5, 5, 8, 9, 7, 5, 5, 5, 5, 5, 8, 5, 5]]
  },
  "prediction_data": {
    "past_grades": [6, 0, 0, 0, 6, 6, 6, 0, 0, 0, 0, 0, 6, 0, 0],
    "required_grades": [7, 0, 0, 0, 7, 7, 7, 0, 0, 0, 0, 0, 7, 0, 0],
    "hours": 20
  }
}
r = requests.post("http://172.28.0.2/", json = inputs)
print(r.text)





Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.








Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


Epoch 1/5
1/1 [==============================] - 1s 1s/step - loss: 241.2777 - acc: 1.0000
Epoch 2/5
1/1 [==============================] - 0s 22ms/step - loss: 241.2545 - acc: 1.0000
Epoch 3/5
1/1 [==============================] - 0s 18ms/step - loss: 241.3365 - acc: 1.0000
Epoch 4/5
1/1 [==============================] - 0s 19ms/step - loss: 241.2930 - acc: 1.0000
Epoch 5/5
1/1 [==============================] - 0s 18ms/step - loss: 241.2658 - acc: 1.0000


172.28.0.2 - - [20/Jan/2020 12:55:56] "POST / HTTP/1.1" 200 -


[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]]
